version: 2

updates:
  - package-ecosystem: pip
    directory: /apps/api
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps-api)"

  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps-web)"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(deps-ci)"
