/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as R403RouteImport } from './routes/403'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedUsersRouteImport } from './routes/_authed/users'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedKnowledgeIndexRouteImport } from './routes/_authed/knowledge/index'
import { Route as AuthedGraphIndexRouteImport } from './routes/_authed/graph/index'
import { Route as AuthedChatIndexRouteImport } from './routes/_authed/chat/index'
import { Route as AuthedSettingsSectionRouteImport } from './routes/_authed/settings/$section'
import { Route as AuthedChatSessionIdRouteImport } from './routes/_authed/chat/$sessionId'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedKnowledgeIndexRoute = AuthedKnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedGraphIndexRoute = AuthedGraphIndexRouteImport.update({
  id: '/graph/',
  path: '/graph/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedChatIndexRoute = AuthedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSettingsSectionRoute = AuthedSettingsSectionRouteImport.update({
  id: '/settings/$section',
  path: '/settings/$section',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedChatSessionIdRoute = AuthedChatSessionIdRouteImport.update({
  id: '/chat/$sessionId',
  path: '/chat/$sessionId',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/403': typeof R403Route
  '/login': typeof LoginRoute
  '/users': typeof AuthedUsersRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/chat/$sessionId': typeof AuthedChatSessionIdRoute
  '/settings/$section': typeof AuthedSettingsSectionRoute
  '/chat/': typeof AuthedChatIndexRoute
  '/graph/': typeof AuthedGraphIndexRoute
  '/knowledge/': typeof AuthedKnowledgeIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/403': typeof R403Route
  '/login': typeof LoginRoute
  '/users': typeof AuthedUsersRoute
  '/': typeof AuthedIndexRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/chat/$sessionId': typeof AuthedChatSessionIdRoute
  '/settings/$section': typeof AuthedSettingsSectionRoute
  '/chat': typeof AuthedChatIndexRoute
  '/graph': typeof AuthedGraphIndexRoute
  '/knowledge': typeof AuthedKnowledgeIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/403': typeof R403Route
  '/login': typeof LoginRoute
  '/_authed/users': typeof AuthedUsersRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/_authed/chat/$sessionId': typeof AuthedChatSessionIdRoute
  '/_authed/settings/$section': typeof AuthedSettingsSectionRoute
  '/_authed/chat/': typeof AuthedChatIndexRoute
  '/_authed/graph/': typeof AuthedGraphIndexRoute
  '/_authed/knowledge/': typeof AuthedKnowledgeIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/login'
    | '/users'
    | '/admin/users'
    | '/chat/$sessionId'
    | '/settings/$section'
    | '/chat/'
    | '/graph/'
    | '/knowledge/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/403'
    | '/login'
    | '/users'
    | '/'
    | '/admin/users'
    | '/chat/$sessionId'
    | '/settings/$section'
    | '/chat'
    | '/graph'
    | '/knowledge'
    | '/settings'
  id:
    | '__root__'
    | '/_authed'
    | '/403'
    | '/login'
    | '/_authed/users'
    | '/_authed/'
    | '/_authed/admin/users'
    | '/_authed/chat/$sessionId'
    | '/_authed/settings/$section'
    | '/_authed/chat/'
    | '/_authed/graph/'
    | '/_authed/knowledge/'
    | '/_authed/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  R403Route: typeof R403Route
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/knowledge/': {
      id: '/_authed/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof AuthedKnowledgeIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/graph/': {
      id: '/_authed/graph/'
      path: '/graph'
      fullPath: '/graph/'
      preLoaderRoute: typeof AuthedGraphIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/chat/': {
      id: '/_authed/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthedChatIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings/$section': {
      id: '/_authed/settings/$section'
      path: '/settings/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof AuthedSettingsSectionRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/chat/$sessionId': {
      id: '/_authed/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof AuthedChatSessionIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedUsersRoute: typeof AuthedUsersRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
  AuthedChatSessionIdRoute: typeof AuthedChatSessionIdRoute
  AuthedSettingsSectionRoute: typeof AuthedSettingsSectionRoute
  AuthedChatIndexRoute: typeof AuthedChatIndexRoute
  AuthedGraphIndexRoute: typeof AuthedGraphIndexRoute
  AuthedKnowledgeIndexRoute: typeof AuthedKnowledgeIndexRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedUsersRoute: AuthedUsersRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
  AuthedChatSessionIdRoute: AuthedChatSessionIdRoute,
  AuthedSettingsSectionRoute: AuthedSettingsSectionRoute,
  AuthedChatIndexRoute: AuthedChatIndexRoute,
  AuthedGraphIndexRoute: AuthedGraphIndexRoute,
  AuthedKnowledgeIndexRoute: AuthedKnowledgeIndexRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  R403Route: R403Route,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
